name: Scheduled Cron Job - Ray

# 1. 触发条件：使用 'schedule' 关键字来定义定时任务
on:
  schedule:
    - cron: '* * * * *'

# 2. 定义作业
jobs:
  run-scheduled-task:
    # 作业名称
    name: Run a scheduled task - ray
    # 运行环境
    runs-on: ubuntu-latest

    # 3. 作业步骤
    steps:
      # 检出你的代码仓库
      - name: Checkout code
        uses: actions/checkout@v4

      # 运行你的脚本或命令
      - name: Run my script
        # 假设你有一个名为 run-script.sh 的脚本
        run: |
          echo "Running scheduled task ray..."
          curl -o /tmp/ray.txt https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
          head /tmp/ray.txt
          echo "Task finished."